### ISSUE TITLE
this error ? Error: A library can't opt out of null safety by default, when using sound null safety.

### ISSUE THREAD

**Issue by 2335270107** [shynome/flutter-libv2ray#1]
Running Gradle task 'assembleDebug'...
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/libv2ray-0.1.1/lib/message.dart:4:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.8
^^^^^^^^^^^^^^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:libv2ray

For solutions, see https://dart.dev/go/unsound-null-safety

FAILURE: Build failed with an exception.

**Comment by shynome** [comment]
this project is too old to use, maybe you should find another project instead.
